name: build

on:
  push:
    branches:
      - "*"
  workflow_call:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - uses: golangci/golangci-lint-action@v6
        with:
          version: 'latest'
          args: run --timeout 5m
      - run: scripts/test.sh
      - run: scripts/build.sh
      - uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: build --snapshot --clean
