name: Release

on:
  release:
    types:
      - created

jobs:
  releaes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v6
        with:
          go-version: '1.25.1'
      - uses: golangci/golangci-lint-action@v8
        with:
          version: 'latest'
          args: run --timeout 5m
      - uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
